# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 18:07
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_commerce', '0003_product_price_moneyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='XYZ', editable=False, max_length=3),
        ),
    ]
