# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce', '0004_product_fields_sku_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock())), default=None),
            preserve_default=False,
        ),
    ]
