# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:12
from __future__ import unicode_literals

from django import VERSION as DJANGO_VERSION
from django.db import migrations

from ..models import CommercePage, CategoryIndexPage

def initial_data(apps, schema_editor):

    category_index_page = CategoryIndexPage(
        title="Category pages",
    )

    commerce_page = CommercePage.objects.first()
    commerce_page.add_child(instance=category_index_page)

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce', '0007_category')
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop),
    ]
