# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailcommerce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce', '0010_product_cost_price_sale_price_moneyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_filter_menu',
            field=models.BooleanField(default=False, verbose_name='search filter menu'),
        )
    ]
